Repository spyder-ide/qtawesome, pull requests merged in 2021-12, with the labels that each got.

#198 PR: Update `load_font` documentation
  qtawesome/__init__.py
  qtawesome/iconic_font.py
Labels: type:Bug, docs

#197 PR: Fix unexpected corruption check except for bundled fonts
  UPDATE.md
  qtawesome/__init__.py
  qtawesome/iconic_font.py
  setupbase.py
Labels: type:Bug

#199 PR: Replace now deprecated distutils with setuptools
  setup.py
  setupbase.py
Labels: type:Task
